### 1) letst import some dependencies

In [2]:
import numpy as np#for numerical calculations
import pandas as pd #`pandas` dealing with data frame and data `preprocessing` to perfome
import matplotlib.pyplot as plt
import seaborn as sns 
#the above liberaries i just import just perfome some operation and for visualisation prospective i will go littel latter 

### 2) importing the dataset

In [4]:
dataset  = pd.read_csv('Data.csv')#just read the data frame which is in csv formate
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X[:,1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, nan],
       [35.0, 58000.0],
       [nan, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

### 3)look at onece missing data😁✔😎

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
#note that we are working simple imputer just on numerical values 

In [16]:
print(X),print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


(None, None)

### 4) Dealing with categoriacal value 👨‍👩‍👦‍👦

##### Encoding categorical data

In [17]:
from sklearn.compose import ColumnTransformer
#features are generated by each transformerwill be concatinated by form a single feature space 


In [18]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),
                                       [0])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
#lets check the data present in X 
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### 5) Encoding dependent variable or data ✔ yes or No 😁😒

In [22]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
#lets check changed target values effected or not while we perform Le

In [26]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### 6) splitting the data into train and test 

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 1)

In [30]:
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [31]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [33]:
print(y_train)

[1 0 0 1 1 0 1]


In [34]:
print(y_test)

[0 1 0]


### 7) Feature Scaling $

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [36]:
#Affter scaling lets see the x_train
print(X_train)

[[0.0 1.0 0.0 -0.038910211282047996 -0.22960023388015188]
 [1.0 0.0 0.0 0.5058327466666259 0.49120534884662787]
 [0.0 0.0 1.0 -0.3112816902563849 -0.4731156334500103]
 [0.0 0.0 1.0 -1.809324824615238 -1.6127677034369463]
 [1.0 0.0 0.0 1.0505757046152997 1.1048641557626704]
 [0.0 1.0 0.0 1.3229471835896367 1.455526331143266]
 [1.0 0.0 0.0 -0.7198389087178904 -0.736112264985457]]


In [37]:
print(X_test)

[[0.0 1.0 0.0 -1.4007676061537326 -1.0867744403660526]
 [1.0 0.0 0.0 -0.4474674297435534 0.05287762962088326]
 [0.0 0.0 1.0 -0.20535944843303158 -1.2621055280563505]]
